INSERT INTO PARAMETER_MANAGEMENT_SERVICE.CONTENT_PARAMETER (
        CREATED_BY,
        CREATED_DATE,
        DESCRIPTION,
        MODIFIED_BY,
        MODIFIED_DATE,
        MODULE,
        NAME,
        VALUE,
        "LANGUAGE",
        "ORDERING",
        LABEL1,
        LABEL2,
        IMAGE_URL,
        ADDITIONAL_DATA,
        FLAG,
        IS_DELETED
    )
VALUES(
        'SYSTEM',
        TIMESTAMP '2023-11-16 15:55:00.000000',
        'Template Receipt Registration Hajj Auto Debit',
        NULL,
        NULL,
        'TEMPLATE_RECEIPT',
        'HAJJ_AUTO_DEBIT',
        '-',
        'IDN',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        'JSON',
        0
    );