INSERT INTO PARAMETER_MANAGEMENT_SERVICE.CONTENT_PARAMETER (
        CREATED_BY,
        CREATED_DATE,
        DESCRIPTION,
        MODIFIED_BY,
        MODIFIED_DATE,
        MODULE,
        NAME,
        VALUE,
        "LANGUAGE",
        "ORDERING",
        LABEL1,
        LABEL2,
        IMAGE_URL,
        ADDITIONAL_DATA,
        FLAG,
        IS_DELETED
    )
VALUES (
        'SYSTEM',
        TIMESTAMP '2023-11-17 10:09:00',
        'Template Receipt Hajj Auto Debit Sukses',
        NULL,
        NULL,
        'TEMPLATE_RECEIPT',
        'HAJJ_AUTO_DEBIT_SUCCESS',
        '-',
        'IDN',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        'JSON',
        '0'
    );